### PR TITLE
Added: Print reaction forces to energyfile

### PR DESCRIPTION
**Pull request by laods**
This is my first dive into IFEM, so this is probably not perfect, but I needed this feature, so I leave it here.

### CODE REVIEW

**Comment by akva2** [comment]
Can one of the admins verify this patch?

**Comment by laods** [comment]
I might have been a little early making a PR out of this. My intention were to make you aware of this patch. Consider it as a WIP until it is verified that it really does what is intended.

**Comment by akva2** [comment]
that's an automated message from jenkins, just ignore it :)

**Comment by akva2** [comment]
and the patch looks fine (to me).

**Comment by kmokstad** [comment]
Joda, er OK dette. Bare en kosmetisk greie at load-headingen bør skrives bare når man har reaksjonskrefter. La inn en separate PR oppå din som fikser dette (får ikke pushe direkte på din branch). Så hvis dette fungerer som det skal kan den commiten squashes med din, før dette merges til master.

**Comment by kmokstad** [comment]
Replaced by #8 which now has been merged

**Pull request closed without merging**
