### PR TITLE
Added: Pre-parsing of input file to read dimension and solver parameters

### PR DESCRIPTION
**Pull request by kmokstad**
Added: Regression test using pre-parsing and crack pressure.

### CODE REVIEW

**Comment by akva2** [comment]
looks fine. personally i wouldn't have used anything as generic as 'solution' for the tag though.

**Comment by akva2** [comment]
jenkins build this please

**Comment by kmokstad** [comment]
Yes, it is a bit too generic perhaps. But I did not find a better covering name. It did not fit within any of the existing tags. If you have a better suggestion I'll happily change it.

**Comment by akva2** [comment]
one suggestion would be

```xml
<fracturedynamics coupling="semiimplicit" formulation="quasistatic"/>
```

**Comment by kmokstad** [comment]
OK, changed to "fracturedynamics" tag instead. But retained the sub-tags for specifying the options.
Can still use "coupling" and "timeintegrator" attributes to specify those integer options directly. Sub-tags only for the most common ones.

**Comment by akva2** [comment]
okay. still inconsistent with the other apps which already have these things but the tag is now sanely named.

**Pull request merged**
