### PR TITLE
Add restart support

### PR DESCRIPTION
**Pull request by akva2**
Requires https://github.com/OPM/IFEM/pull/449

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this ifem=310 please

**Comment by akva2** [comment]
jenkins build this ifem=310 please

**Comment by akva2** [comment]
jenkins build this ifem=310 please

**Comment by akva2** [comment]
jenkins build this ifem=310 please

**Comment by akva2** [comment]
jenkins build this ifem=310 please

**Comment by akva2** [comment]
jenkins build this ifem=310 please

**Comment by akva2** [comment]
jenkins build this ifem=449 please

**Comment by akva2** [comment]
jenkins build this ifem=449 please

**Comment by akva2** [comment]
jenkins build this ifem=449 ifem-poroelasticity=48 please

**Comment by kmokstad** [comment]
Replaced by #57 which now have been merged.

**Pull request closed without merging**
